apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: viper-app-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
  labels:
    app: viper-app
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - workshop.vipercloud.cc
    secretName: viper-app-tls
  rules:
  - host: workshop.vipercloud.cc
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: viper-app
            port:
              number: 3000
