apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    type: mysql-storage
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/k8s_mysql_data
