apiVersion: v1
kind: Secret
metadata:
  name: viper-app-secret
  labels:
    app: viper-app
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: MTExVFgydnZoVmlmcVpAQ00xSmt4a1drbkQ0VExZc3pSN2FE
  MYSQL_PASSWORD: MTExVFgydnZoVmlmcVpAQ00xSmt4a1drbkQ0VExZc3pSN2FE
  DB_PASSWORD: MTExVFgydnZoVmlmcVpAQ00xSmt4a1drbkQ0VExZc3pSN2FE
  SENDGRID_API_KEY: U0cuakQ2b2JUMExRci1ienNjaE92VElUdy5NeTFKaU9rRjFicGpKLU1NckI3T0Vyb1NBdl9mNzNrME1lbEgyem5oYlRF
  MAILERSEND_API_KEY: bWxzbi5hYmVmNTM2MWZkN2E2OGZjYzJjYTM3OTlkYjdlMTIwNTQxNWQyNjYwMGZiNGEzOTVmZGVkNDY1NDgyYzk0M2Y4
  GOOGLE_AUTH_CLIENT_ID: NTQzMTM1NDk1MjcwLTdkYmpmcnVibWpwYWw4aHRwNTRsNm5vOHNsbjFuNXJ0LmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29t
  GOOGLE_AUTH_CLIENT_SECRET: R09DU1BYLUxId3dPMk9vTVRvc0JfdS12VTR1Z0xBbDh2eQ==
  APP_COOKIE_SECRET: cG9wdWxhci1jYXNzZXR0ZS1iYWNrc2hpZnQtc2hha2luZXNz
  # Initial admin credentials (created on first run if no admin exists)
  INITIAL_ADMIN_USERNAME: YWRtaW4=
  INITIAL_ADMIN_EMAIL: YWRtaW5AZXhhbXBsZS5jb20=
  INITIAL_ADMIN_PASSWORD: Q2hhbmdlTWVPbkZpcnN0TG9naW4xMjMh
